name: Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./planningPokerUi
    
    steps:
    - name: Angular Github Actions
      uses: mayur-rawte/github-angular-actions@latest
