name: PokerApp API [Master]
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Test

    runs-on: ubuntu-latest
    env:
      working-directory: ./planningpoker
 
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        working-directory: ${{env.working-directory}}
        run: dotnet build --configuration Release
      - name: Test with dotnet
        working-directory: ${{env.working-directory}}
        run: dotnet test --configuration Release
